CREATE TABLE PUBLIC.DISH
(
    ID PRIMARY KEY BIGSERIAL,
    NAME char (50) NOT NULL UNIQUE,
    PRICE INTEGER NOT NULL CHECK (PRICE > 0 AND PRICE <= 5000)
)

CREATE TABLE PUBLIC.INGREDIENT
(
    ID PRIMARY KEY BIGSERIAL,
    NAME char (50) NOT NULL UNIQUE,
    UNIT_MEASUREMENT CHAR (50), NOT NULL
)

CREATE TABLE PUBLIC.USERS
(
    ID PRIMARY KEY BIGSERIAL,
    NAME CHAR (50) NOT NULL,
    SURNAME CHAR (50) NOT NULL,
    CITY CHAR (50),
    BIRTHDAY DATE NOT NULL,
    LOGIN CHAR (50) NOT NULL UNIQUE,
    PASSWORD CHAR (50) NOT NULL,
    ROLE CHAR (50) NOT NULL
)

CREATE TABLE PUBLIC.ORDERS
(
    ID PRIMARY KEY BIGSERIAL, 
    DISH_ID INTEGER NOT NULL,
    USER_ID INTEGER NOT NULL,
    COURIER_ID INTEGER NOT NULL,
    ORDER_DATE DATE NOT NULL,
    DELIVERED BOOLEAN DEFAULT FALSE, 
    STAR_GRADE INTEGER CHEK (STAR_GRADE > 0 AND STAR_GRADE <= 5),
    ADD CONSTRAINT FK_COURIER FOREIGN KEY (COURIER_ID) REFERENCES USERS(ID),
    ADD CONSTRAINT FK_DISH FOREIGN KEY (DISH_ID) REFERENCES DISH(ID),
    ADD CONSTRAINT FK_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
)

CREATE TABLE PUBLIC.dISH_INGREDIENT
(
    DISH_ID INTEGER NOT NULL,
    INGREDIENT_ID INTEGER NOT NULL,
    UNIT_MEASUREMENT_VALUE FLOAT NOT NULL,
    PRIMARY KEY (DISH_ID, INGREDIENT_ID),
    FOREIGN KEY (DISH_ID) REFERENCES DISH(ID),
    FOREIGN KEY (INGREDIENT_ID) REFERENCES INGREDIENT(ID)
)

-- Initialization of a single admin of application for delivery of food
-- INSERT INTO USERS VALUE (1, "Имя Отчество", "Фамилия", "Город", 1900-01-01, "admin", "*******", "ADMIN");